//! Autogenerated weights for pallet_mev_protection
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_mev_protection.
pub trait WeightInfo {
    fn submit_protected_tx() -> Weight;
    fn execute_protected_tx() -> Weight;
    fn cancel_protected_tx() -> Weight;
}

/// Weights for pallet_mev_protection using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: MevProtection PendingProtectedTxs (r:0 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn submit_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: MevProtection PendingProtectedTxs (r:1 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn execute_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4665`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 4665)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: MevProtection PendingProtectedTxs (r:1 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn cancel_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4665`
        // Minimum execution time: 10_000_000 picoseconds.
        Weight::from_parts(11_000_000, 4665)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: MevProtection PendingProtectedTxs (r:0 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn submit_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: MevProtection PendingProtectedTxs (r:1 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn execute_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4665`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 4665)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: MevProtection PendingProtectedTxs (r:1 w:1)
    /// Proof: MevProtection PendingProtectedTxs (max_values: None, max_size: Some(1200), added: 3675, mode: MaxEncodedLen)
    fn cancel_protected_tx() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4665`
        // Minimum execution time: 10_000_000 picoseconds.
        Weight::from_parts(11_000_000, 4665)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}